name: Trivy Docker Image Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f dockerfile \
            -t trivy-demo:${{ github.sha }} .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: image
          image-ref: trivy-demo:${{ github.sha }}
          scanners: vuln
          severity: CRITICAL,HIGH
          ignore-unfixed: false
          exit-code: 1
          format: table

jitu singh
10:44 AM
name: Trivy Docker Image Scan

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f dockerfile \
            -t trivy-demo:${{ github.sha }} .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: image
          image-ref: trivy-demo:${{ github.sha }}
          scanners: vuln
          severity: CRITICAL,HIGH
          ignore-unfixed: false
          exit-code: 1
          format: table
